CC = g++
CCFLAGS = -std=c++11

SOURCE_EJERCICIO_1 = ejercicio-1/algoritmo_exacto.cpp
TARGET_EJERCICIO_1 = ej1
SOURCE_EJERCICIO_2_GOLOSO = ejercicio-2/srcEj2/ej2Jugador.cpp
SOURCE_EJERCICIO_2_RANDOM = ejercicio-2/srcEj2/random_player.cpp
TARGET_EJERCICIO_2_GOLOSO = ej2
TARGET_EJERCICIO_2_RANDOM = random
SOURCE_EJERCICIO_3 = ejercicio-3/ej3.cpp
TARGET_EJERCICIO_3 = ej3
SOURCE_CARPETA_SRC_EXACTO = src/algoritmo_exacto.cpp
SOURCE_CARPETA_SRC_GOLOSO = src/ej2Jugador.cpp
TARGET_CARPETA_SRC_EXACTO = src_exacto
TARGET_CARPETA_SRC_GOLOSO = src_goloso

all: ejercicio1 ejercicio2_goloso ejercicio2_random ejercicio3

ejercicio1:
	$(CC) $(CCFLAGS) -o $(TARGET_EJERCICIO_1) $(SOURCE_EJERCICIO_1)

ejercicio2_goloso:
	$(CC) $(CCFLAGS) -o $(TARGET_EJERCICIO_2_GOLOSO) $(SOURCE_EJERCICIO_2_GOLOSO)

ejercicio2_random:
	$(CC) $(CCFLAGS) -o $(TARGET_EJERCICIO_2_RANDOM) $(SOURCE_EJERCICIO_2_RANDOM)

ejercicio3:
	$(CC) $(CCFLAGS) -o $(TARGET_EJERCICIO_3) $(SOURCE_EJERCICIO_3)

scr_exacto:
	$(CC) $(CCFLAGS) -o $(TARGET_CARPETA_SRC_EXACTO) $(SOURCE_CARPETA_SRC_EXACTO)

scr_goloso:
	$(CC) $(CCFLAGS) -o $(TARGET_CARPETA_SRC_GOLOSO) $(SOURCE_CARPETA_SRC_GOLOSO)


clean:
	$(RM) $(TARGET_EJERCICIO_1) $(TARGET_EJERCICIO_2_GOLOSO) \
	$(TARGET_EJERCICIO_2_RANDOM) $(TARGET_EJERCICIO_3) $(TARGET_CARPETA_SRC_EXACTO) \
	$(TARGET_CARPETA_SRC_GOLOSO)
