all: algoritmo_exacto random_player

algoritmo_exacto:
	g++ -std=c++11 algoritmo_exacto.cpp -o algoritmo_exacto

random_player:
	g++ -std=c++11 random_player.cpp -o random_player

clean:
	rm -f algoritmo_exacto *.o *~
	rm -f random_player *.o *~