all: algoritmo_goloso random_player

algoritmo_goloso:
	g++ -std=c++11 ej2Jugador.cpp -o ej2

random_player:
	g++ -std=c++11 random_player.cpp -o random_player

clean:
	rm -f algoritmo_goloso *.o *~
	rm -f random_player *.o *~
